### ISSUE TITLE
DysonInvalidAuth exception

### ISSUE THREAD

**Issue by gmathur** [shenxn/libdyson#24]
After installing all the requirements, consistently running into the following error.

Please choose your account region
1: Mainland China
2: Rest of the World
Region [1/2]: 2
Region code: US
Email: xyz@xyz.com
Traceback (most recent call last):
  File "get_devices.py", line 22, in <module>
    verify = account.login_email_otp(email, region)
  File "/Users/gmathur/Downloads/libdyson/libdyson/cloud/account.py", line 127, in login_email_otp
    auth=False,
  File "/Users/gmathur/Downloads/libdyson/libdyson/cloud/account.py", line 114, in request
    raise DysonInvalidAuth
libdyson.exceptions.DysonInvalidAuth

**Comment by marcoleder** [comment]
See the following issues:

[https://github.com/shenxn/ha-dyson/issues/59](url)
[https://github.com/shenxn/ha-dyson/issues/59#issuecomment-938498433](url)
[https://github.com/shenxn/libdyson/issues/15](url)

Maybe they help

Best, Marco

**Comment by johnypony3** [comment]
@gmathur (and to anyone that comes here): `Log out of your app and wait 5 minutes`

@marcoleder it would be easier to say "Log out of your app and wait 5 minutes".

**Comment by mcnutter1** [comment]
Same issue, this has worked before but now doesnt... the waiting 5 minutes after logging out of the app doesn't work either.,

**Comment by daVid0n** [comment]
hello guys - same with me, trying the entire day already, it still seems to go the same path, the get_devices.py work flawlessly by triggering the login, i get the code via mail but then always directly "libdyson.exceptions.DysonInvalidAuth".
Logging back into the app is then not possible due to too many attempts. 
100% sure my information is correct, so may it be broken on Dyson's side meanwhile?

**Comment by kelp545** [comment]
@daVid0n Did you get it??
