### ISSUE TITLE
libdyson.exceptions.DysonServerError

### ISSUE THREAD

**Issue by virusman** [shenxn/libdyson#41]
`get_devices.py` consistently returns an error for me. Initially it was returning `libdyson.exceptions.DysonInvalidAuth`, then I logged out of the app, and now it returns `libdyson.exceptions.DysonServerError` all the time.

# Log
```
Please choose your account region
1: Mainland China
2: Rest of the World
Region [1/2]: 2
Region code: US
Email: ...
Traceback (most recent call last):
  File "/Users/virusman/Private/code/python/libdyson/get_devices.py", line 22, in <module>
    verify = account.login_email_otp(email, region)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/virusman/Private/code/python/libdyson/libdyson/cloud/account.py", line 122, in login_email_otp
    response = self.request(
               ^^^^^^^^^^^^^
  File "/Users/virusman/Private/code/python/libdyson/libdyson/cloud/account.py", line 116, in request
    raise DysonServerError
libdyson.exceptions.DysonServerError
```

**Comment by virusman** [comment]
I also can't login via the app anymore after signing out. Logging in to the website works.

**Comment by Henry4234** [comment]
same here.
is anything wrong in dyson server?

**Comment by dotvezz** [comment]
@Henry4234 @virusman: This is most likely related to a login bug that was resolved in https://github.com/libdyson-wg/libdyson-neon, which is a continuation of this project which fixes some bugs and adds small improvements.

If you're using this with Home Assistant, you can use https://github.com/libdyson-wg/ha-dyson, a continuation of the counterpart Home Assistant integrations which incorporates both the cloud and local parts, and also incorporates the libdyson fixes.

If you have any questions, feel free to let me know; I'm the core maintainer.

**Comment by Kill0geR** [comment]
With this Project you can easily connect to your Dyson fan https://github.com/Kill0geR/DysonPythonHack

**Comment by Kill0geR** [comment]
> I also can't login via the app anymore after signing out. Logging in to the website works.

With this Project you can easily connect to your Dyson fan https://github.com/Kill0geR/DysonPythonHack
