### ISSUE TITLE
get_devices.py missing argument `backend`

### ISSUE THREAD

**Issue by Ulrar** [shenxn/libdyson#5]
Hi,

My dyson local integration started reporting everything as unavailable, so I figured I'd delete then re-add it.
Unfortunately I can't get get_devices.py to work anymore, after entering my verification code I always get :

```
Traceback (most recent call last):
  File "get_devices.py", line 30, in <module>
    devices = account.devices()
  File "/dev/libdyson/libdyson/cloud/account.py", line 178, in devices
    devices.append(DysonDeviceInfo.from_raw(raw))
  File "/dev/libdyson/libdyson/cloud/device_info.py", line 31, in from_raw
    decrypt_password(raw["LocalCredentials"]),
  File "/dev/libdyson/libdyson/cloud/utils.py", line 24, in decrypt_password
    cipher = Cipher(
TypeError: __init__() missing 1 required positional argument: 'backend'
```

```
$ python3 --version
Python 3.8.6
```

Thanks

**Comment by Ulrar** [comment]
I fixed it by adding this to the top of `libdyson/cloud/utils.py`
```
from cryptography.hazmat                    import backends
```

And then adding the default backend to the Cipher like this : 
```
    cipher = Cipher(algorithms.AES(DYSON_ENCRYPTION_KEY), modes.CBC(DYSON_ENCRYPTION_INIT_VECTOR), backend = backends.default_backend())
```

**Comment by shenxn** [comment]
Check your cryptography package version. Is it older than version 3.1?

**Comment by shenxn** [comment]
Can you pull the new code and redo `pip install -r requirements.txt`? This should fix your problem.
